spring:
  application:
    name: truedom
  datasource:
    url: ${POSTGRES_URL:jdbc:h2:mem:truedom;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASSWORD:}
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  batch:
    job:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  port: ${PORT:8080}
